BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Entry] (
    [id] NVARCHAR(1000) NOT NULL,
    [content] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Entry_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Entry_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
