name: Send Daily Prompt

on:
  schedule:
    - cron: '8 * * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1.1.1
      with:
        args: https://gratitudejournalapp.azurewebsites.net/api/SendPrompt
